# version: "3.8"

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks: ['demo']
  restart: unless-stopped
  ports:
    - 11434:11434
  volumes:
    - ollama:/root/.ollama

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['demo']
  container_name: ollama-pull-llama
  volumes:
    - ollama:/root/.ollama
  entrypoint: /bin/sh
  environment:
    - OLLAMA_HOST=ollama:11434
  command:
    - "-c"
    - "sleep 3; ollama pull gemma3:1b"

services:
  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama
    container_name: ollama

  ollama-pull-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    container_name: ollama-pull
    depends_on:
      - ollama-cpu

  llm-router-local:
    build: .
    container_name: llm-router
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - ollama-pull-cpu
    networks:
      - demo
    ports:
      - "11411:11411"
    environment:
      - OLLAMA_HOST=ollama-cpu:11434
    restart: unless-stopped

volumes:
  ollama:

networks:
  demo: