version: "3.8"

services:
  ollama:
    build:
      context: ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  llm-router-local:
    build: .
    container_name: llm-router-local
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      ollama:
        condition: service_started
    restart: unless-stopped

volumes:
  ollama: